routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

//Route::resource('threads', 'ThreadsController');


Route::get('/threads', 'ThreadsController@index')->name('threads.index');
Route::get('/threads/create', 'ThreadsController@create')->name('threads.create');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/threads/{channel}/{thread}', 'ThreadsController@show')->name('threads.show');
Route::delete('/threads/{channel}/{thread}', 'ThreadsController@destroy')->name('threads.destroy');
Route::post('/threads', 'ThreadsController@store')->name('threads.store');
Route::get('/threads/{channel}', 'ThreadsController@index');
Route::post('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@store')->middleware('auth');
Route::delete('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@destroy')->middleware('auth');

Route::post('/threads/{channel}/{thread}/replies', 'RepliesController@store')->name('replies.store');
Route::get('/threads/{channel}/{thread}/replies', 'RepliesController@index')->name('replies.index');
Route::post('/replies/{reply}/favorite', 'FavoritesController@store');
Route::delete('/replies/{reply}/favorite', 'FavoritesController@destroy');
Route::delete('/replies/{id}', 'RepliesController@destroy')->name('replies.destroy');
Route::patch('/replies/{id}', 'RepliesController@update')->name('replies.update');
Route::get('/profiles/{user}', 'ProfilesController@show');
Route::delete('/profiles/{user}/notifications/{notification}', 'UserNotificationsController@destroy');
Route::get('/profiles/{user}/notifications/', 'UserNotificationsController@index');

app/Thread.php
<?php

namespace App;

use App\Events\ThreadHasNewReply;
use App\Notifications\ThreadWasUpdated;
use function foo\func;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{

    use RecordsActivity;

    protected $guarded = [];

    protected $with = ['creator', 'channel'];

    protected $appends = ['isSubscribedTo'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(function ($builder) {

            $builder->withCount('replies');

        });

        static::deleting(function($thread) {

            $thread->replies->each->delete();

        });
    }

    public function replies()

    {

        return $this->hasMany(Reply::class);

    }


    public function creator()

    {

        return $this->belongsTo(User::class, 'user_id');

    }


    /**
     * @param $reply
     * @return Model
     */
    public function addReply($reply)

    {

        $reply = $this->replies()->create($reply);
        $this->notifySubscribers($reply);
        return $reply;

    }

    public function notifySubscribers($reply)
    {
        $this->subscriptions

            ->where('user_id', '!=', $reply->user_id)
            ->each
            ->notify($reply);
    }

    public function channel()

    {

        return $this->belongsTo(Channel::class);

    }

    public function path()

    {

        return "/threads/{$this->channel->slug}/{$this->id}";
//        return '/threads/'. $this->channel->slug . '/' . $this->id;

    }

    public function scopeFilter($query, $filters)
    {

        return $filters->apply($query);

    }

    /**
     * @param null $user_id
     * @return $this
     */
    public function subscribe($user_id = null)
    {
        $this->subscriptions()->create([

            'user_id' => $user_id ?: auth()->id()

        ]);

        return $this;
    }

    public function unsubscribe($user_id = null)
    {
        $this->subscriptions()
            ->where('user_id', $user_id ?: auth()->id())
            ->delete();
    }

    public function subscriptions()
    {

        return $this->hasMany(ThreadSubscription::class);

    }

    public function getIsSubscribedToAttribute()
    {

        return $this->subscriptions()
            ->where('user_id', auth()->id())
            ->exists();


    }

    public function hasUpdatesFor($user)
    {
        $key = $user->visitedThreadCacheKey($this);

        return $this->updated_at > cache($key);
    }

}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Channel;
use App\Inspections\Spam;
use App\Thread;
use App\ThreadFilters;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class ThreadsController extends Controller
{

    public function __construct()
    {

        $this->middleware('auth')->except(['index', 'show']);

    }

    /**
     * Display a listing of the resource.
     *
     * @param \App\Channel $channel
     * @param \App\ThreadFilters $filters
     * @return \Illuminate\Http\Response
     */
    public function index(Channel $channel, ThreadFilters $filters)
    {

        $threads = $this->getThreads($channel, $filters);

        if(request()->wantsJson()) {

            return $threads->get();

        }

        return view('threads.index', compact('threads'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('threads.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Spam $spam
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request, Spam $spam)
    {

        $this->validate($request, [
            'title' => 'required',
            'channel_id' => 'required|exists:channels,id'
        ]);

        $spam->detect([
            request('body'),
            request('title'),
        ]);

        $thread = new Thread;
        $thread->user_id = auth()->id();
        $thread->title = $request->title;
        $thread->body = $request->body;
        $thread->channel_id = $request->channel_id;
        $thread->save();
        return redirect($thread->path())
            ->with('flash', 'Your thread has been published!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channel, Thread $thread)
    {
        if(auth()->check()) {
            auth()->user()->read($thread);
        }

        return view('threads.show', [

            'thread' => $thread,

        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param $channel
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        $thread->delete();

        if(request()->wantsJson()) {
            return response([], 204);
        }

        return redirect('/threads');

    }

    /**
     * @param Channel $channel
     * @param ThreadFilters $filters
     * @return mixed
     */
    public function getThreads(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);

        if ($channel->exists) {

            $threads->where('channel_id', $channel->id);

        }



        if(request()->wantsJson()) {

            return $threads;

        }

        $threads = $threads->get();
        return $threads;
    }
}

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create a new thread</div>

                    <div class="card-body">
                        <form action="{{ route('threads.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="channel_id">Chose channel:</label>
                                <select name="channel_id" id="channel_id" class="form-control">
                                    @foreach ($channels as $channel)
                                        <option value="{{ $channel->id }}">{{ $channel->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="title">Title:</label>
                                <input type="text" name="title" class="form-control" id="title" placeholder="title" value="{{ old('title') }}">
                            </div>

                            <div class="form-group">
                                <label for="body">Body:</label>
                                <textarea type="body" name="body" class="form-control" id="body" placeholder="title">{{ old('body') }}</textarea>
                            </div>

                            <input type="submit" class="btn btn-success" value="Publish">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Forum threads</div>

                    <div class="card-body">
                       @forelse($threads as $thread)
                           <div class="level">
                               <article>
                                   <h4>
                                       <a href="{{ $thread->path() }}">
                                           @if(auth()->check() && $thread->hasUpdatesFor(auth()->user()))
                                               <strong>{{ $thread->title }}</strong>
                                           @else
                                               {{ $thread->title }}
                                           @endif
                                       </a>
                                   </h4>
                                   <div class="body">{{ $thread->body }}</div>
                               </article>

                               <a href="{{ $thread->path() }}">
                                   {{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
                               </a>
                           </div>

                           <hr />
                        @empty
                           <p>There are no relevant results at this time</p>
                       @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/reply.blade.php
<reply :attributes="{{ $reply }}"
       v-cloak
       update_route="{{ route('replies.update', $reply->id)}}"
       destroy_route="{{ route('replies.destroy', $reply->id)}}"
       inline-template>

</reply>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
    <thread-view initial-replies-count="{{ $thread->replies_count }}" inline-template>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <a href="/profiles/{{ $thread->creator->name }}">{{ $thread->creator->name }}</a> posted:
                            {{ $thread->title }}
                            @can('update', $thread)
                            <form action="{{ $thread->path() }}" method="POST">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-link">Delete thread</button>
                            </form>
                            @endcan
                        </div>

                        <div class="card-body">
                            {{ $thread->body }}
                        </div>
                    </div>

                    <replies
{{--                            :data="{{ $thread->replies }}"--}}
                            @added="repliesCount++"
                            @removed="repliesCount--"
                    >

                    </replies>
                    {{--@foreach($replies as $reply)--}}
    {{--                    @include('threads.reply')--}}
                    {{--@endforeach--}}

                    {{--{{ $replies->links() }}--}}


                </div>

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <p>
                                This thread was published {{ $thread->created_at->diffForHumans() }} by
                                <a href="/profiles/{{ $thread->creator->name }}">{{ $thread->creator->name }}</a>, and currently
                                has <span v-text="repliesCount"></span> {{ str_plural('comment', $thread->replies_count ) }}.
                            </p>

                            <p>
                                <subscribe-button :active="{{ json_encode($thread->isSubscribedTo) }}"></subscribe-button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </thread-view>
@endsection